# Official documentation at http://goreleaser.com
project_name: http-downloader
builds:
  - env:
      - CGO_ENABLED=0
    binary: hd
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
      - 6
    goos:
      - windows
      - linux
      - darwin
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
    ldflags:
      - -X github.com/linuxsuren/cobra-extension/version.version={{.Version}}
      - -X github.com/linuxsuren/cobra-extension/version.commit={{.ShortCommit}}
      - -X github.com/linuxsuren/cobra-extension/version.date={{.Date}}
      - -w
      - -s
dist: release
archives:
  - name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
      arm64: arm64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: hd
    tap:
      owner: linuxsuren
      name: homebrew-linuxsuren
    folder: Formula
    homepage: "https://github.com/linuxsuren/http-downloader"
    description: HTTP download tool
    dependencies:
      - name: bash-completion
        type: optional
    test: |
      version_output = shell_output("#{bin}/hd version")
      assert_match version.to_s, version_output
    install: |
      bin.install name

      prefix.install_metafiles
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "surenpi/hd:latest-amd64"
      - "surenpi/hd:{{.Tag}}-amd64"
      - "ghcr.io/linuxsuren/hd:latest-amd64"
      - "ghcr.io/linuxsuren/hd:{{.Tag}}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/LinuxSuRen/http-downloader"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "surenpi/hd:latest-arm64"
      - "surenpi/hd:{{.Tag}}-arm64"
      - "ghcr.io/linuxsuren/hd:latest-arm64"
      - "ghcr.io/linuxsuren/hd:{{.Tag}}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/LinuxSuRen/http-downloader"
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: ghcr.io/linuxsuren/hd:{{.Tag}}
    image_templates:
      - ghcr.io/linuxsuren/hd:{{.Tag}}-amd64
      - ghcr.io/linuxsuren/hd:{{.Tag}}-arm64
  - name_template: ghcr.io/linuxsuren/hd:latest
    image_templates:
      - ghcr.io/linuxsuren/hd:latest-amd64
      - ghcr.io/linuxsuren/hd:latest-arm64
  - name_template: surenpi/hd:latest
    image_templates:
      - surenpi/hd:latest-amd64
      - surenpi/hd:latest-arm64
  - name_template: surenpi/hd:{{.Tag}}
    image_templates:
      - surenpi/hd:{{.Tag}}-amd64
      - surenpi/hd:{{.Tag}}-arm64